config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/okay/admin', as: 'rails_admin'
  devise_for :users
  resources :pools do
    resources :vestings
  end
  root 'home#index'
  get '/prices', to: "home#prices"
  post '/prices', to: "home#prices"

  get '/pricesmodel', to: "prices#index"
  post '/pricesmodel', to: "prices#update"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :user
  has_many :vestings, dependent: :destroy

  validates :project, presence: true, uniqueness: { scope: :user_id }
  validates :amount, numericality: { greater_than: 0 }
  validates :price, numericality: { greater_than: 0 }, allow_nil: true

  paginates_per 10
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :set_pool, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: %i[ show edit update destroy ]

  # GET /pools or /pools.json
  def index
    @search = current_user.pools.ransack(params[:q])
    @pools = @search.result.order(launchdate: :desc).page params[:page]
  end

  # GET /pools/1 or /pools/1.json
  def show
  end

  # GET /pools/new
  def new
    #pool = Pool.new
    @pool = current_user.pools.build()
  end

  # GET /pools/1/edit
  def edit
  end

  # POST /pools or /pools.json
  def create
    #@pool = Pool.new(pool_params)
    @pool = current_user.pools.build(pool_params)

    respond_to do |format|
      if @pool.save
        format.html { redirect_to pool_url(@pool), notice: "Pool was successfully created." }
        format.json { render :show, status: :created, location: @pool }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pools/1 or /pools/1.json
  def update
    respond_to do |format|
      if @pool.update(pool_params)
        format.html { redirect_to pool_url(@pool), notice: "Pool was successfully updated." }
        format.json { render :show, status: :ok, location: @pool }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1 or /pools/1.json
  def destroy
    @pool.destroy

    respond_to do |format|
      format.html { redirect_to pools_url, notice: "Pool was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @pool = current_user.pools.find_by(id: params[:id])
    redirect_to pools_path if @pool.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pool
      begin
        @pool = current_user.pools.find(params[:id])
      rescue
        redirect_to pools_path
      end
    end

    # Only allow a list of trusted parameters through.
    def pool_params
      params.require(:pool).permit(:project, :round, :platform, :amount, :price, :vesting, :launchdate, :profit, :user_id)
    end
end

app/helpers/pools_helper.rb
module PoolsHelper
  def pool_profit(pool)
    profit = 0
    @pool = pool
    pool.vestings.find_each do |vesting|
      profit += vesting.return unless vesting.return.nil?
    end
    pool.amount.nil? ? 0 : (profit - pool.amount).round(0)
  end

  def total_profit(user)
    total = 0
    user.pools.each do |pool|
      total += pool_profit(pool)
    end
    return total
  end
end

app/views/pools/_form.html.erb
<div class="row justify-content-center">
  <div class="col-lg-8 col-xl-7">
    <%= form_with(model: pool) do |form| %>
      <% if pool.errors.any? %>
        <div style="color: red" class="mb-2">
          <h5><%= pluralize(pool.errors.count, "error") %> prohibited this pool from being saved:</h5>

          <ul>
            <% pool.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-floating">
        <%= form.text_field :project, class:"form-control", placeholder:"Project" %>
        <%= form.label :project, "Project" %>
      </div>

      <div class="form-floating">
        <%= form.text_field :round, class:"form-control", placeholder:"Select the round" %>
        <%= form.label :round, "Round" %>
      </div>

      <div class="form-floating">
        <%= form.text_field :platform, class:"form-control", placeholder:"Round" %>
        <%= form.label :platform, "Platform" %>
      </div>

      <div class="form-floating">
        <%= form.number_field :amount, class:"form-control", placeholder:"Your fund" %>
        <%= form.label :amount, "Your Amount" %>
      </div>

      <div class="form-floating">
        <%= form.number_field :price, step: :any, class:"form-control", placeholder:"Token price" %>
        <%= form.label :price, "Token Price" %>
      </div>

      <div class="form-floating">
        <%= form.text_area :vesting, class:"form-control", placeholder:"Vesting time" %>
        <%= form.label :vesting, "Vesting Schedule:" %>
      </div><br/>

      <div>
        <%= form.label :launchdate, "Launch Date:", style:"color: #6c757d; font-size:1.5rem;" %>
        <% if @pool.launchdate.nil? %>
          <%= form.date_select :launchdate, selected: Date.today, include_blank: true, start_year: Date.today.year - 2, end_year: Date.today.year + 3 %>
        <% else %>
          <%= form.date_select :launchdate, start_year: Date.today.year - 2, end_year: Date.today.year + 3 %>
        <% end %>
      </div>

      <div>
        <br/>
        <%= form.submit "Confirm", class:"btn btn-primary" %>
        <%= link_to "Cancel", pools_path, class: "btn btn-secondary" %>
      </div>
      <div class=" mt-4">
        <%= link_to "Delete", @pool, method: :delete, data: { confirm: "Do you really want to close this pool?"}, class: "btn btn-danger" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pools/_pool.html.erb
<div id="<%= dom_id pool %>">
  <tr class="text-center">
    <td><%= link_to pool.project, pool %></td>
    <td><%= pool.round %></td>
    <td><%= pool.platform %></td>
    <td>$<%= number_with_delimiter(pool.amount.round(0)) unless pool.amount.nil? %></td>
    <td><%= pool.price.nil? ? "-" : "$" %><%= pool.price %></td>
    <% if pool_profit(pool) == 0 %>
      <td>-</td>
      <% elsif pool_profit(pool) < 0 %>
      <td style="color: red;">
    <% else %>
      <td style="color: blue;">
    <% end %>
    <%= number_with_delimiter(pool_profit(pool)) %>$</td>
    <td class="text-start"><%= link_to pool.vesting, pool_vestings_path(pool) %></td>
    <td><%= pool.launchdate.nil? ? "Updating..." : pool.launchdate.strftime('%d/%m/%Y') %></td>
  </tr>
</div>

app/views/pools/edit.html.erb
<% content_for :title, "Update Pool" %>
<h2 class="masthead-heading text-center text-uppercase text-secondary mb-0">Update Pool</h2>
<div class="divider-custom">
  <div class="divider-custom-line"></div>
  <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
  <div class="divider-custom-line"></div>
</div>

<div class="px-4">
  <%= render "form", pool: @pool %><br/>
</div>

app/views/pools/index.html.erb
<% content_for :title, "Pools" %>
<div class="container mb-4">
  <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">My Pools</h2>
  <div class="divider-custom">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
    <div class="divider-custom-line"></div>
  </div>

  <div class="mb-3">
    <%= search_form_for @search do |f| %>
      <%#= f.label :project_or_platform_cont, "Project/Platform:" %>
      <%= f.search_field :project_or_platform_cont, placeholder:"Project or Platform" %>

      <%= f.submit %>
    <% end %>
  </div>

  <div class="table-responsive">
    <table class="table table-hover table-bordered">
      <thead class="table-dark text-center">
        <tr class="align-middle">
          <th><%= sort_link(@search, :project,'Project') %></th>
          <th><%= sort_link(@search, :round,'Round') %></th>
          <th><%= sort_link(@search, :platform,'Platform') %></th>
          <th><%= sort_link(@search, :amount,'Amount') %></th>
          <th><%= sort_link(@search, :price,'Price') %></th>
          <th>Profit</th>
          <th>Vesting Schedule</th>
          <th><%= sort_link(@search, :launchdate,'Launch Date') %></th>
        </tr>
      </thead>
      <tbody>
        <%= render @pools %>
        <tr class="text-center border-0">
          <td colspan="3" class="text-end border-0"><b>Total:</b></td>
          <td class="border-0"><b>$<%= number_with_delimiter(current_user.pools.sum("amount").round(0), delimiter: ",") %><b></td>
          <td class="border-0"></td>
          <td class="border-0"><b>
            <% if total_profit(current_user) == 0 %>
              <span>
            <% elsif total_profit(current_user) < 0 %>
              <span style="color: red;">
            <% else %>
              <span style="color: blue;">
            <% end %>
            <%= number_with_delimiter(total_profit(current_user)) %>$</span></b></td>
          <td class="border-0"></td>
          <td class="border-0"></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="text-end mb-0">
    <%= link_to_prev_page @pools, '< Prev' %>&nbsp;
    <%= link_to_next_page @pools, 'Next >' %>
  </div>
  <div>
    <%= link_to "New Project", new_pool_path, class:"btn btn-sm btn-primary" %>
  </div>
</div>

app/views/pools/new.html.erb
<% content_for :title, "New Pool" %>
<h2 class="masthead-heading text-center text-uppercase text-secondary mb-0">New Pool</h2>
<div class="divider-custom">
  <div class="divider-custom-line"></div>
  <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
  <div class="divider-custom-line"></div>
</div>

<div class="px-4">
  <%= render "form", pool: @pool %><br/>
</div>

app/views/pools/show.html.erb
<% content_for :title, "Pool Details" %>
<h2 class="masthead-heading text-center text-uppercase text-secondary mb-0"><%= @pool.project %></h2>
<div class="divider-custom">
  <div class="divider-custom-line"></div>
  <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
  <div class="divider-custom-line"></div>
</div>
<div class="row justify-content-center">
  <div class="col-md-6 col-lg-4 mb-4">
    <div class="text-center">
      <i class="fa-solid fa-flag fa-3x"></i>
      <p class="mb-1">Round</p>
      <h6><%= @pool.round %></h6>
    </div>
  </div>

  <div class="col-md-6 col-lg-4 mb-4">
    <div class="text-center">
      <i class="fa fa-rocket fa-3x"></i>
      <p class="mb-1">Platform</p>
      <h6><%= @pool.platform %></h6>
    </div>
  </div>

  <div class="col-md-6 col-lg-4 mb-4">
    <div class="text-center">
      <i class="fa-solid fa-handshake-simple fa-3x"></i>
      <p class="mb-1">Amount</p>
      <h6><%= @pool.amount.round(0) unless @pool.amount.nil? %> $</h6>
    </div>
  </div>

  <div class="col-md-6 col-lg-4 mb-4">
    <div class="text-center">
      <i class="fa-solid fa-circle-dollar-to-slot fa-3x"></i>
      <p class="mb-1">Token Price</p>
      <h6><%= @pool.price %> $</h6>
    </div>
  </div>

  <div class="col-md-6 col-lg-4 mb-4">
    <div class="text-center">
      <i class="fa-regular fa-calendar-check fa-3x"></i>
      <p class="mb-1">Launch Date</p>
      <h6><%= @pool.launchdate.nil? ? "Updating..." : @pool.launchdate.strftime('%d/%m/%Y') %></h6>
    </div>
  </div>

  <div class="col-md-6 col-lg-4 mb-4">
    <div class="text-center">
      <i class="fa-solid fa-sack-dollar fa-3x"></i>
      <p class="mb-1">Profit</p>
      <% if pool_profit(@pool) == 0 %>
        <h6>-</h6>
      <% elsif pool_profit(@pool) < 0 %>
        <h6 style="color: red;"><%= pool_profit(@pool) %> $</h6>
      <% else %>
        <h6 style="color: blue;"><%= pool_profit(@pool) %> $</h6>
      <% end %>
    </div>
  </div>
</div>

<br/>
<div class="text-center">
  <h5>
    <i class="fa-solid fa-bell fa-1x"></i>
    <span><%= link_to "Vesting Schedule:", pool_vestings_path(@pool) %> <%= @pool.vesting %></span>
  </h5>
</div>
<br/>
<h5 class="text-center">
<%= link_to "Update", edit_pool_path(@pool), class:"btn btn-sm btn-primary" %>
<%= link_to "Back", pools_path, class:"btn btn-sm btn-secondary" %>
</h5><br/>