config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/okay/admin', as: 'rails_admin'
  devise_for :users
  resources :pools do
    resources :vestings
  end
  root 'home#index'
  get '/prices', to: "home#prices"
  post '/prices', to: "home#prices"

  get '/pricesmodel', to: "prices#index"
  post '/pricesmodel', to: "prices#update"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/vesting.rb
class TotalRateValidator < ActiveModel::Validator
  def validate(vesting)
    if vesting.id.nil?
      if (vesting.pool.vestings.sum(:rate) + vesting.rate) > 100
        vesting.errors.add :base, "Total vesting rate is over 100%"
      end
    else
    # When commit update, we have rate of old value: Vesting.find(vesting.id).rate and new value: vesting.rate
      if (vesting.pool.vestings.sum(:rate) - Vesting.find(vesting.id).rate + vesting.rate ) > 100
        vesting.errors.add :base, "Total vesting rate is over 100%"
      end
    end
  end
end

class Vesting < ApplicationRecord
  belongs_to :pool

  validates :date, uniqueness: { scope: :pool_id }
  validates :rate, presence: true, numericality: { greater_than: 0}
  validates :soldtoken, :return, numericality: { greater_than: 0}, allow_nil: true
  validates_with TotalRateValidator

  paginates_per 10
end

app/controllers/vestings_controller.rb
class VestingsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_pool
  before_action :set_vesting, only: %i[ show edit update destroy ]
  # GET /vestings or /vestings.json
  def index
    @vestings = @pool.vestings.order(:date).page params[:page]
  end

  # GET /vestings/new
  def new
    @vesting = @pool.vestings.build()

    @defaut_date = !@pool.vestings.second_to_last.nil? ? @pool.vestings.second_to_last.date : Date.today
    @defaut_rate = !@pool.vestings.second_to_last.nil? ? @pool.vestings.second_to_last.rate : 0
  end

  # GET /vestings/1/edit
  def edit
  end



  # POST /vestings or /vestings.json
  def create
    @vesting = @pool.vestings.build(vesting_params)

    respond_to do |format|
      if @vesting.save
        format.html { redirect_to pool_vestings_path notice: "Vesting was successfully created." }
        format.json { render :show, status: :created, location: @vesting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vesting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vestings/1 or /vestings/1.json
  def update
    respond_to do |format|
      if @vesting.update(vesting_params)
        format.html { redirect_to pool_vestings_path, notice: "Vesting was successfully updated." }
        format.json { render :show, status: :ok, location: @vesting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vesting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vestings/1 or /vestings/1.json
  def destroy
    @vesting.destroy

    respond_to do |format|
      format.html { redirect_to pool_vestings_path(@pool), notice: "Vesting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def get_pool
      begin
        @pool = current_user.pools.find(params[:pool_id])
      rescue #if this pool does not belong to current_user, back to pools
        redirect_to pools_path if @pool.nil?
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_vesting
      @vesting = @pool.vestings.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vesting_params
      params.require(:vesting).permit(:date, :rate, :soldtoken, :return, :pool_id )
    end
end

app/helpers/vestings_helper.rb
module VestingsHelper
  def token_recieve(vesting)
    if vesting.pool.price.nil? || vesting.rate.nil?
      return "-"
    else
      total_token = vesting.pool.amount / vesting.pool.price
      return (vesting.rate*total_token/100).round(0)
    end
  end
end

app/views/vestings/_form.html.erb
<%= form_with(model: vesting, url: [@pool, vesting]) do |form| %>
  <% if vesting.errors.any? %>
    <div style="color: red" class="mb-2">
      <h5><%= pluralize(vesting.errors.count, "error") %> prohibited this vesting from being saved:</h5>
      <ul>
        <% vesting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if params[:action] == "edit" || params[:action] == "update" %> <!--Only display when edit vesting-->
    <div class="form-floating">
      <%= form.number_field :soldtoken, class:"form-control", placeholder:"Token sold" %>
      <%= form.label "Token Sold" %>
    </div><br>
    <div class="form-floating">
      <%= form.number_field :return, step: :any, class:"form-control", placeholder:"Recieve, $" %>
      <%= form.label "Recieve, $" %>
    </div><br>
  <% end %>

  <div class="row">
    <div class="col-md-6 justify-content-center">
      <%= form.label "Vesting date: ", class:"mb-3", style:"color: #6c757d; font-size:1.1rem;" %><br>
      <%= form.date_select :date, default: @defaut_date, start_year: Date.today.year - 2, end_year: Date.today.year + 5 %>
    </div>

    <div class="form-floating col-md-6">
    <% if params[:action] == "new" %>
      <%= form.number_field :rate, step: :any, value: @defaut_rate, class:"form-control", placeholder:"Rate, %" %>
    <% else %>
      <%= form.number_field :rate, step: :any, class:"form-control", placeholder:"Rate, %" %>
    <% end %>
      <%= form.label "Rate, %" %>
    </div>
  </div><br>

  <div>
    <%= form.submit "OK", class:"btn btn-primary" %>
    <%= link_to "Cancel", pool_vestings_path(@pool), class:" btn btn-secondary" %>
  </div>
<% end %>

app/views/vestings/_vesting.html.erb
<div id="<%= dom_id vesting %>">
  <tr class="text-center">
    <th><%= link_to "Vesting #{@k}", edit_pool_vesting_path(@pool, vesting) %></th>
    <td>
      <% if vesting.date < Date.current %>
        <s>
      <% end %>
      <%= vesting.date.strftime('%d/%m/%Y') %></s>
    </td>
    <td><%= vesting.rate.round(2) unless vesting.rate.nil? %> %</td>
    <td><%= number_with_delimiter(token_recieve(vesting)) %></td>
    <td><%= number_with_delimiter(vesting.soldtoken.round(0)) unless vesting.soldtoken.nil? %></td>
    <td><%= number_with_delimiter(vesting.return.round(0)) unless vesting.return.nil? %></td>
  </tr>
</div>

app/views/vestings/edit.html.erb
<% content_for :title, "Update Vesting" %>
<div class="container mb-4">
  <div class="masthead-heading text-center text-uppercase text-secondary mb-0">
    <h2><%= @pool.project %></h2>
    <h5>Update vesting</h5>
  </div>
  <div class="divider-custom">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
    <div class="divider-custom-line"></div>
  </div>
  <div class="px-3">
    <%= render "form", vesting: @vesting %><br/>

    <%= link_to "Delete this vesting", [@pool, @vesting], method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-sm btn-danger" %>
  </div>
</div>

app/views/vestings/index.html.erb
<% content_for :title, "Vestings" %>
<div class="container mb-4">
  <div class="masthead-heading text-center text-uppercase text-secondary mb-0">
    <h2>Vesting Schedule</h2>
    <h4><%= @pool.project %></h4>
  </div>
  <div class="divider-custom mb-2">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
    <div class="divider-custom-line"></div>
  </div>
  <h5 class="text-center"><%= @pool.vesting %></h5>

  <div class="table-responsive">
    <table class="table table-hover table-bordered ps-2">
      <thead class="table-dark text-center">
        <tr class="align-middle">
          <th>Vesting</th>
          <th>Date</th>
          <th>Rate</th>
          <th>Recieve Token</th>
          <th>Sold Token</th>
          <th>Recieve, $</th>
        </tr>
      </thead>
      <tbody>
        <% @k = @vestings.current_page*10 - 10 + 1 %>
        <% @vestings.sort_by(&:date).each do |vesting| %>
          <%= render vesting %>
          <% @k += 1 %>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="text-end mb-0">
    <%#= paginate @vestings, window: 2 %>
    <%= link_to_prev_page @vestings, '< Prev' %>&nbsp;
    <%= link_to_next_page @vestings, 'Next >' %>
  </div>
  <div>
    <%= link_to "New Vesting", new_pool_vesting_path(@pool), class:"btn btn-sm btn-primary" %>
    <%= link_to "Back", pools_path, class:"btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/vestings/new.html.erb
<% content_for :title, "New Vesting" %>
<div class="container mb-4">
  <div class="masthead-heading text-center text-uppercase text-secondary mb-0">
    <h2><%= @pool.project %></h2>
    <h5>New vesting</h5>
  </div>
  <div class="divider-custom">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
    <div class="divider-custom-line"></div>
  </div>
  <div class="px-3">
    <%= render "form", pool: @pool, vesting: @vesting %>
  </div>
</div>