config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/okay/admin', as: 'rails_admin'
  devise_for :users
  resources :pools do
    resources :vestings
  end
  root 'home#index'
  get '/prices', to: "home#prices"
  post '/prices', to: "home#prices"

  get '/pricesmodel', to: "prices#index"
  post '/pricesmodel', to: "prices#update"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'net/http'
  require 'json'

  # Grab News
  def index

    url = "https://min-api.cryptocompare.com/data/v2/news/?lang=EN"
    uri = URI(url)
    respone = Net::HTTP.get(uri)
    @news = JSON.parse(respone)
  end

  # Grab Prices
  def prices

  url_price = "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=250&page=1&sparkline=false&price_change_percentage=1h%2C24h"
  uri_price = URI(url_price)
  respone_price = Net::HTTP.get(uri_price)
  #@respone_price['Authorization'] = '67595558-d5e2-4224-a42a-fb880e9458ca'
  @prices = JSON.parse(respone_price)

  url_top_search = "https://api.coingecko.com/api/v3/search/trending"
  uri_top_search = URI(url_top_search)
  respone_top_search = Net::HTTP.get(uri_top_search)
  @top_search = JSON.parse(respone_top_search)

  uri_btc = URI("https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd")
  respone_btc = Net::HTTP.get(uri_btc)
  @price_btc = JSON.parse(respone_btc)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer class="text-center text-lg-start text-white mt-auto"
        style="background-color: #2c3e50;">
  <div class="p-3 pb-0">
    <div class="row">
      <div class="col-lg-4 mt-2 mb-0 text-center">
        <a
           class="btn btn-outline-light btn-social m-1"
           href="#"
           role="button"
           ><i class="fab fa-facebook-f"></i
          ></a>
        <a
           class="btn btn-outline-light btn-social m-1"
           href="#"
           role="button"
           ><i class="fab fa-twitter"></i
          ></a>
        <a
           class="btn btn-outline-light btn-social m-1"
           href="https://t.me/loki9x"
           role="button"
           ><i class="fab fa-telegram"></i
          ></a>
        <a
           class="btn btn-outline-light btn-social m-1"
           href="#"
           role="button"
           ><i class="fab fa-github"></i
          ></a>
      </div>

      <div class="col-lg-4 mb-2 text-center" data-bs-toggle="modal" data-bs-target="#portfolioModal1">
        <a class="btn btn-outline-light btn-coffee m-1"
           role="button"><i class="fas fa-mug-hot fa-1x"></i></a><br/>
        Buy me a coffee!
      </div>
      <div class="col-lg-4 mt-2 text-center">
        <p class="d-flex justify-content-center align-items-center">
          <%= link_to '<i class="fa-solid fa-users"></i> Sign up free!'.html_safe, new_user_registration_path, class:"btn btn-outline-light btn-rounded" %>
        </p>
      </div>
    </div>
  </div>

  <div class="copyright text-center p-2">
    <small>Copyright &copy; MyInvests 2022</small>
  </div>

  <div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-md">
      <div class="modal-content">
        <div class="modal-header border-0" style="font-size: 1rem;"><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div>
        <div class="modal-body text-center pb-3">
          <div class="container">
            <!-- Modal - Title-->
            <h2 class="text-secondary mb-0">Coffee Lover</h2>
            <!-- Icon Divider-->
            <div class="divider-custom mb-1">
              <div class="divider-custom-line"></div>
              <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
              <div class="divider-custom-line"></div>
            </div>
            <!-- Modal - Image-->
            <p style="color: black;" class="text-center mb-0">MB Bank</p>
            <%= image_tag ("coffee/mbbank.jpg"), size: "200", class:"img-fluid rounded mb-1" %>
            <div>
              <button class="btn btn-primary mt-3" data-bs-dismiss="modal">
                Thank you <i class="fa-solid fa-hands-clapping"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/home/_header.html.erb
<header class="masthead bg-primary text-white text-center">
  <div class="container d-flex align-items-center flex-column">
    <!-- Masthead Avatar Image-->
    <%= image_tag ("avataaars.svg"), class:"masthead-avatar mb-5" %>
    <!-- Masthead Heading-->
    <h1 class="masthead-heading text-uppercase mb-0">Tuyen Pham</h1>
    <!-- Icon Divider-->
    <div class="divider-custom divider-light">
      <div class="divider-custom-line"></div>
      <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
      <div class="divider-custom-line"></div>
    </div>
    <!-- Masthead Subheading-->
    <p class="masthead-subheading font-weight-light mb-0">Influencer - Web Developer - Physics</p>
  </div>
</header>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-secondary text-uppercase fixed-top" id="mainNav">
  <div class="container mb-0">
    <%= image_tag "logo_transparent.png", size: "60" %>
    <%= link_to "My Invests", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu<i class="fas fa-bars"></i>
    </button><br>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item"><%= link_to "News", root_path, class:"nav-link px-lg-2 rounded" %></li>
        <li class="nav-item"><%= link_to "Market", prices_path, class:"nav-link px-lg-2 rounded" %></li>
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to "Pools", pools_path, class:"nav-link px-lg-2 rounded" %></li>
          <li class="mx-0 mx-lg-1" ><%= link_to current_user.email, edit_user_registration_path, class:"nav-link px-lg-2 rounded" %></li>
          <li class="nav-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link px-lg-2 rounded" %></li>
          <% if current_user.admin? %>
            <li class="nav-item"><%= link_to "Admin", rails_admin.index_path(User), class:"nav-link px-lg-2 rounded" %></li>
          <% end %>
        <% else %>
          <li class="mx-0 mx-lg-1"><%= link_to "Login", new_user_session_path, class:"nav-link px-lg-2 rounded" %></li>
          <li class="nav-item"><%= link_to "Register", new_user_registration_path, class:"nav-link px-lg-2 rounded" %></li>
        <% end %>
      </ul>
      </div>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<% content_for :title, "Home" %>

<div class="container">
  <h3 class="page-section-heading text-center align-middle text-uppercase text-secondary mb-0">Lastest News</h3>
  <div class="divider-custom">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
    <div class="divider-custom-line"></div>
  </div>
  <div class="row align-items-center mb-1">
    <% @news["Data"].first(30).each do |article| %>
      <div class="col-sm-auto mx-auto">
        <div class="d-flex flex-row align-items-center" style="max-width: 32rem; height: 10rem;">
          <div class="p-2">
            <a href="<%= article["url"] %>" style="text-decoration: none; color:inherit;">
            <img src="<%= article["imageurl"] %>" class="card-img" alt="img" style="width: 6.5rem;">
          </div>
          <div class="p-2">
            <div class="card-body">
              <h6 class="card-title"><%= article["title"] %></h6></a>
              <p class="card-text" style="font-size: 0.75rem;"><span class="text-muted">
                <%= article["source"].capitalize %> |
                <%= time_ago_in_words(Time.at(article["published_on"].to_i)).capitalize %> ago</span>
              </p>
           </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/prices.html.erb
<% content_for :title, "Market" %>
<div class="container">
  <div class="d-flex no-wrap" style="font-size:0.9rem;">
    <strong><i class="fa-brands fa-hotjar" style="color:red;"></i>&nbsp;&nbsp;</strong>  Trending:&nbsp;&nbsp;
    <marquee scrollamount="2">
      <% @top_search["coins"].each do |coin| %>
        <%= image_tag coin["item"]["large"], size:"25" %>
        <%= coin["item"]["name"] %>:
        $<%= coin["item"]["price_btc"].to_d*@price_btc["bitcoin"]["usd"] < 0.001 ? (coin["item"]["price_btc"].to_d*@price_btc["bitcoin"]["usd"]).round(6) : (coin["item"]["price_btc"].to_d*@price_btc["bitcoin"]["usd"]).round(2) %>&nbsp;
      <% end %>
    </marquee>
  </div>

  <div class="table-responsive">
    <table id="pricesTable" class="table align-middle text-end table-hover mb-0">
      <thead class="align-middle">
        <tr>
          <th class="text-center">Rank</th>
          <th></th>
          <th class="text-start">Name</th>
          <th>Price</th>
          <th class="text-center">1H</th>
          <th class="text-center">24H</th>
          <th style="min-width: 80px;">Mkt Cap</th>
          <th style="min-width: 80px;">Supply</th>
          <th style="min-width: 80px;">24H Volume</th>
        </tr>
      </thead>
        <tbody>
        <% @prices.each do |token| %>
        <tr>
          <td class="text-center"><%= token["market_cap_rank"] %></td>
          <td class="px-0"><%= image_tag token["image"], size:"30" %></td>
          <td class="text-start">
              <%= token["name"] %><br>
              <i style="font-size: 0.8rem;"><%= token["symbol"].upcase %></i>
          </td>
          <td>$<%= token["current_price"] < 0.001 ? number_with_delimiter(token["current_price"].to_d.round(8)) : number_with_delimiter(token["current_price"].round(2)) %></td>
          <% token["price_change_percentage_1h_in_currency"] ||= 0 %>
          <% if token["price_change_percentage_1h_in_currency"] >= 0 %>
            <td style="color: green;">
          <% else %>
            <td style="color: red;">
          <% end %>
            <%= token["price_change_percentage_1h_in_currency"].round(2) %>%
          </td>
          <% if token["price_change_percentage_24h_in_currency"] >= 0 %>
            <td style="color: green;">
          <% else %>
            <td style="color: red;">
          <% end %>
            <%= token["price_change_percentage_24h_in_currency"].round(2) %>%
          </td>
          <td>$<%= number_to_human(token["market_cap"]) %></td>
          <td>
            <%= number_to_human(token["circulating_supply"]) %><br/>
            <i style="font-size: 0.8rem; color: darkgray;"><%= number_to_human(token["total_supply"]) %></i>
          </td>
          <td>$<%= number_to_human(token["total_volume"]) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <script>
      document.addEventListener('DOMContentLoaded', function () {
        let table = new DataTable('#pricesTable')
      });
    </script>
  </div>
</div>